tester2/config/routes.rb
Rails.application.routes.draw do
  resources :supervises
  resources :faculties
  resources :f_rates
  resources :colleges
  resources :c_rates
  resources :programs
  resources :work_ins
  resources :departments
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'starting/new'

  get 'starting/index'

  get 'starting/start'

  get 'sessions/login'

  get 'users/signup'

  get 'welcome/index'

  resources :clients

  root 'welcome#index'

  get 'signup'  => 'users#signup'
  resources :users

  get 'login' => 'sessions#login'
  resources :sessions

  post 'login' => 'sessions#create'

  post 'start' => 'starting#start'

  delete 'logout' => 'sessions#destroy'

  get 'start' => 'starting#start'

  get 'index' => 'starting#index'

  get 'results' => 'starting#results'

  get 'profile' => 'users#profile'
  resources :users

  get 'users/destroy_account' => 'users#destroy_account'

  delete '/profile' => 'users#destroy_account'

  get 'modifyCurrentStatus' => 'users#modifyCurrentStatus'
  resources :users

  post 'modifyCurrentStatus' => 'users#modifyCurrentStatus'

  get 'modifyEmail' => 'users#modifyEmail'
  resources :users

  post 'modifyEmail' => 'users#modifyEmail'

  get 'modifyFirstName' => 'users#modifyFirstName'
  resources :users

  post 'modifyFirstName' => 'users#modifyFirstName'

  get 'modifyLastName' => 'users#modifyLastName'
  resources :users

  post 'modifyLastName' => 'users#modifyLastName'

  get 'modifyUsername' => 'users#modifyUsername'
  resources :users

  post 'modifyUsername' => 'users#modifyUsername'

  get 'modifyYear' => 'users#modifyYear'
  resources :users

  post 'modifyYear' => 'users#modifyYear'
  
  get 'modifyShowComments' => 'users#modifyShowComments'
  resources :users

  post 'modifyShowComments' => 'users#modifyShowComments'
  
  get 'collegeProfile' => 'starting#collegeProfile'
  resources :starting
  
  get 'rateThisCollege' => 'starting#rateThisCollege'
  resources :starting
  
  post 'rateThisCollege' => 'starting#rateThisCollege'
end

tester2/app/controllers/starting_controller.rb
class StartingController < ApplicationController

  before_action :require_user, :index

  @@table = Array.new(5)
  @@tb = Hash.new()

  def start
     @connection = ActiveRecord::Base.connection
     @@table = Array.new(5)
    if params[:commit] == "Search"
      if !params[:starting][:College].empty?
        @st1='exec searchcollege '+'@college ='+'\'"'+params[:starting][:College]+'"\''
        @result1 = @connection.exec_query(@st1)
        @@table.push(@result1)
      else @@table.push(Hash.new())
      end
      if !params[:starting][:Department].empty?
        @st2='exec searchdepartment '+'@department = '+'\'"'+params[:starting][:Department]+'"\''
        @result2 = @connection.exec_query(@st2)
        @@table.push(@result2)
      else @@table.push(Hash.new())
      end
      if !params[:starting][:Program].empty?
        @st3='exec searchprogram '+'@program = '+'\'"'+params[:starting][:Program]+'"\''
        @result3 = @connection.exec_query(@st3)
        @@table.push(@result3)
      else @@table.push(Hash.new())
      end
      if !params[:starting][:Faculty].empty?
        @st4='exec searchfaculty '+'@faculty = '+'\'"'+params[:starting][:Faculty]+'"\''
        @result4 = @connection.exec_query(@st4)
        @@table.push(@result4)
      else @@table.push(Hash.new())
      end
      redirect_to '/results'
      
      else if params[:commit] == "Check College With Rank"
           if !params[:starting][:start].empty? and !params[:starting][:end].empty?
              @st5='exec ranksearchcollege '+'@start = '+params[:starting][:start]+','
              @st5=@st5+'@end = '+params[:starting][:end]
        @result5 = @connection.exec_query(@st5)
        @@table[0,4] = [Hash.new(), Hash.new(), Hash.new(), Hash.new()]
        @@table.push(@result5)
        end
        redirect_to '/results'
    end
    
    end
  end

  def index

  end

  def results
    @rslt = Array.new(5)
    count = 0
    @@table.compact.each do |item|
      @rslt[count] = item
      count = count + 1
    end
    @result1 = @rslt[0]
    @result2 = @rslt[1]
    @result3 = @rslt[2]
    @result4 = @rslt[3]
    @result5 = @rslt[4]
  end
  
  def collegeProfile
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue
      @current_user = nil;
    end
    if @current_user
      @collegename = params[:college]
      @imagurl = params[:imgurl] || nil
      @connection = ActiveRecord::Base.connection
      @st1='exec searchcollege '+'@college ='+'\'"'+ @collegename +'"\''
      @st2 = 'exec getRatingAndComments ' + '@college ='+'\''+ @collegename + '\'' + ","
      @st2 = @st2 + '@username = ' + '\''+ @current_user.username + '\''
      
      @st3 = 'exec getPublicComments ' + '@college ='+'\''+ @collegename + '\'' + ","
      @st3 = @st3 + '@username = ' + '\''+ @current_user.username + '\''
      
      @result = @connection.exec_query(@st1)
      @resultst2 = @connection.exec_query(@st2)
      @resultst3 = @connection.exec_query(@st3)
      
      puts @resultst3
      
    else
      redirect_to '/'
    end
  end
  
  def rateThisCollege
    @collegenameforrate = params[:collegename]
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue
      @current_user = nil;
    end
    if @current_user
    if params[:commit] == "Submit This Rate"
      if params[:starting][:rate] == "norate"
        rating = "NULL"
      else
        rating = params[:starting][:rate]
      end
      @connection = ActiveRecord::Base.connection
      @st1='exec AddCRate '+ '@college ='+'\''+ params[:original] + '\'' + ","
      @st1 = @st1 + '@username = ' + '\''+ @current_user.username + '\'' + ","
      @st1 = @st1 + '@rate = ' + rating + ","
      @st1 = @st1 + '@comment = ' + '\'' + params[:starting][:comment_on_college] + '\''
      @result = @connection.exec_query(@st1)
      url = '/collegeProfile?college=' + params[:original]
      redirect_to URI.encode(url)
    end
    else
      redirect_to '/'
    end
  end
end

tester2/app/helpers/starting_helper.rb
module StartingHelper
end

tester2/app/views/starting/collegeProfile.html.erb
<html>
	<h1 align="left"><%= @collegename%></h1>
	<div class = "Profile" align="left">
	<% if !@imagurl.nil? %>
	<img src= <%= @imagurl %> height="200" width="200" />
	<br />
	<% end %>
	<% @result.each do |p| %>
		<% p.each do |k, v| %>
			<% if k != "imgURL"%>
				<strong><%= k%></strong> : <%= v%>
				<br />
			<% end %>
		<% end %>
	<% end %>
	
	<h3>Your Comments on <%= @collegename %></h3>
	<% @resultst2.each do |p| %>
		<% p.each do |k, v| %>
			<li><%= v %></li>
		<% end %>
	<% end %>
	
	<h3>Public Comments on <%= @collegename %></h3>
	<% @resultst3.each do |p| %>
		<li><%= p["Username"]%> : <%= p["Comment"] %></li>
	<% end %>	
	<br />
	<%= button_to "Rate And Comment On This University", "/rateThisCollege?collegename=" + @collegename , class: "testersignup"%>
	<%= button_to "Go to Main Search", "/start", class: "testersignup"%>
	</div>
</html>

tester2/app/views/starting/index.html.erb
<style>

body {
  text-align: center;
 }
 
 nav {
 	text-align: right;
 	margin: 10px;
 }
#section {
	position: absolute;
    top: 50%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%);
    margin: 0 auto; 
}

input {
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;	
	height: 30px;
}

.logandsign {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background-color:transparent;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #000000;
	display:inline-block;
	cursor:pointer;
	color:#000000;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:0px 1px 0px #ffffff;
}

.logandsign:hover {
	background-color: #D3D3D3;
	color: #000000;
}

.logandsign:active {
	position:relative;
	top:1px;
}

</style>
<html>
	<head><link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Indie Flower">
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Architects Daughter">
      <style>
      body {
  		text-align: center;
  		font-family: 'Indie Flower', serif;
        font-size: 25px;
 	  }
 	  .logandsign {
 	  	font-family: 'Architects Daughter', serif;
 	  	font-size: 15px; 
 	  }
 	  </style>  
      </head>
      
      
		<body>
		
		<div id = "section">
			<h1> Graduate School </h1>
			<h2> Planning the Next Milestone</h2>
		  	<a href="login" class="logandsign">Log In</a>
		  	<a href="signup" class="logandsign">Sign Up</a>
		
		</div>
		
		</body>

</html>

tester2/app/views/starting/new.html.erb
<h1>Starting#new</h1>
<p>Find me in app/views/starting/new.html.erb</p>

tester2/app/views/starting/rateThisCollege.html.erb
<html>
	<h1><%= @collegenameforrate %></h1>
	<%= form_for(:starting, url: "/rateThisCollege") do |f| %>
	  <%= hidden_field_tag :original, @collegenameforrate  %>
	  <strong><p>Your Rate: </p></strong>
	  <%= f.radio_button :rate, 'norate', :checked => true %> 
	  <%= label :rate_norate, 'No Rate' %>
	  <%= f.radio_button :rate, '1' %>
	  <%= label :rate_first, '1' %>
	  <%= f.radio_button :rate, '2' %>
	  <%= label :rate_second, '2' %>
	  <%= f.radio_button :rate, '3' %>
	  <%= label :rate_third, '3' %>
	  <%= f.radio_button :rate, '4' %>
	  <%= label :rate_fourth, '4' %>
	  <strong><p>Your Comment: </p></strong>
	  <%= f.text_area :comment_on_college, size: "60x12", :placeholder => "Comment On This University" %>
	  <br />
	  <br />
	  <%= f.submit "Submit This Rate", class: "testersignup" %>
	<% end %>
	<br />
	<%= button_to "Go to Main Search", "/start", class: "testersignup"%>
</html>

tester2/app/views/starting/results.html.erb
<style>
	td {
		width: 50px;
		border: solid;
	}
	
	th {
		width: 50px;
		border: solid;
	}
	
	a.button {
	    -moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
		-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
		box-shadow:inset 0px 1px 0px 0px #ffffff;
		background-color:transparent;
		-moz-border-radius:6px;
		-webkit-border-radius:6px;
		border-radius:6px;
		border:1px solid #000000;
		display:inline-block;
		cursor:pointer;
		color:#000000;
		font-weight:bold;
		padding:6px 24px;
		text-decoration:none;
		text-shadow:0px 1px 0px #ffffff;
	}
	
	a.button:hover {
		background-color: #D3D3D3;
		color: #000000;
	}
</style>
<% if (!@result1.is_a?(Hash) || !@result1.empty?) && !@result1.nil?%>
	<% @result1.each do |p| %>
	
	<% if (!p.nil?) && !p.empty? %>
		<% puts p %>
		<table style="table-layout: fixed; width:400; border-style: solid;">
	<tr>
	<% p.keys.each do |k|%>
	<% if k != "imgURL"%>
		<th><%= k %></th>
	<% end %>
	<% end %>
	</tr>
	<tr>
	<% p.each do |k, v|%>
	<% if k == "College name"%>
		<% if !p["imgURL"].nil? %>
		<td><%= link_to v, "/collegeProfile?college="+ v + "&imgurl=" + p["imgURL"] %></td>
		<% else %>
		<td><%= link_to v, "/collegeProfile?college="+ v %></td>
		<% end %>
	<% else %>
	<% if k != "imgURL"%>
		<td><%= v%></td>
	<% else %>
	<% end %>
	<% end %>
	<% end %>
	</tr>
	  </table>
	  <h1> </h1>
	  <h1> </h1>
	  <h1> </h1>
	  <% end %>
	  <% end %>
<% end %>

<% if (!@result2.is_a?(Hash) || !@result2.empty?) && !@result2.nil?%>
	<% count = 0 %>
	<table style="table-layout: fixed; width:400; border-style: solid;">
	<% @result2.each do |p| %>
	
	<% if (!p.nil?) && !p.empty? %>
		<% puts p %>
	<% if count == 0 %>
	<tr>
	<% p.keys.each do |k|%>
		<th><%= k %></th>
	<% end %>
	</tr>
	<% count = count + 1 %>
	<% end %>
	<tr>
	<% p.values.each do |v|%>
		<td><%= v %></td>
	<% end %>
	</tr>
	  
	  <% end %>
	  <% end %>
	  </table>
	  <h1> </h1>
	  <h1> </h1>
	  <h1> </h1>
<% end %>

<% if (!@result3.is_a?(Hash) || !@result3.empty?) && !@result3.nil?%>
	<% count = 0 %>
	<table style="table-layout: fixed; width:400; border-style: solid;">
	<% @result3.each do |p| %>
	
	<% if (!p.nil?) && !p.empty? %>
		<% puts p %>
	<% if count == 0 %>
	<tr>
	<% p.keys.each do |k|%>
		<th><%= k %></th>
	<% end %>
	</tr>
	<% count = count + 1 %>
	<% end %>
	<tr>
	<% p.values.each do |v|%>
		<td><%= v %></td>
	<% end %>
	</tr>
	  
	  <% end %>
	  <% end %>
	  </table>
	  <h1> </h1>
	  <h1> </h1>
	  <h1> </h1>
<% end %>

<% if (!@result4.is_a?(Hash) || !@result4.empty?) && !@result4.nil?%>
	<% count = 0 %>
	<table style="table-layout: fixed; width:400; border-style: solid;">
	<% @result4.each do |p| %>
	
	<% if (!p.nil?) && !p.empty? %>
		<% puts p %>
	<% if count == 0 %>
	<tr>
	<% p.keys.each do |k|%>
		<th><%= k %></th>
	<% end %>
	</tr>
	<% count = count + 1 %>
	<% end %>
	<tr>
	<% p.values.each do |v|%>
		<td><%= v %></td>
	<% end %>
	</tr>
	  
	  <% end %>
	  <% end %>
	  </table>
	  <h1> </h1>
	  <h1> </h1>
	  <h1> </h1>
<% end %>

<% if (!@result5.is_a?(Hash) || !@result5.empty?) && !@result5.nil?%>
	<% count = 0 %>
	<table style="table-layout: fixed; width:400; border-style: solid;">
	<% @result5.each do |p| %>
	
	<% if (!p.nil?) && !p.empty? %>
		
	<% if count == 0 %>
	<tr>
	<% p.keys.each do |k|%>
		<th><%= k %></th>
	<% end %>
	</tr>
	<% count = count + 1 %>
	<% end %>
	<tr>
	<% p.values.each do |v|%>
		<td><%= v %></td>
	<% end %>
	</tr>
	  
	  <% end %>
	  <% end %>
	  </table>
	  <h1> </h1>
	  <h1> </h1>
	  <h1> </h1>
<% end %>
<a href="/start" class="button">Go to Main Search</a>

tester2/app/views/starting/start.html.erb
<style>
body {
  text-align: center;
 }
 
 nav {
 	text-align: right;
 	margin: 10px;
 }
#section {
	position: absolute;
	padding-top: 300px;
    top: 50%;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, -50%);
    margin: 0 auto; 
}
input {
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;	
	height: 30px;
}
.logandsign {
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff;
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff;
	box-shadow:inset 0px 1px 0px 0px #ffffff;
	background-color:transparent;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #000000;
	display:inline-block;
	cursor:pointer;
	color:#000000;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:0px 1px 0px #ffffff;
}
.logandsign:hover {
	background-color: #D3D3D3;
	color: #000000;
}
.logandsign:active {
	position:relative;
	top:1px;
}
</style>
<html>
	<head><link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Indie Flower">
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Architects Daughter">
      <style>
      body {
  		text-align: center;
  		font-family: 'Indie Flower', serif;
        font-size: 25px;
 	  }
 	  .logandsign {
 	  	font-family: 'Architects Daughter', serif;
 	  	font-size: 15px; 
 	  }
 	  </style>  
      </head>
      
		<body>
		
		<div id = "section">
			<h1> Graduate School </h1>
			<h2> Planning the Next Milestone</h2>
			<h3> Search</h3>
			
			
			
	 <%= form_for(:starting, url: start_path) do |f| %> 
	  <%= f.text_field :College, :placeholder => "College" %> 
	  <br />
	  <br />
	  <%= f.text_field :Department, :placeholder => "Department" %> 
	  <br />
	  <br />
	  <%= f.text_field :Program, :placeholder => "Program" %> 
	  <br />
	  <br />
	  <%= f.text_field :Faculty, :placeholder => "Faculty" %> 
	  <br />
	  <br />
	  <%= f.submit "Search", class: "testersignup" %>
	  
	  <h3> Or </h3>
	   <h3> Search College With Ranking </h3>
	   <%= f.text_field :start, :placeholder => "Start rank" %> 
	  <br />
	  <br />
	  <%= f.text_field :end, :placeholder => "End rank" %> 
	  <br />
	  <br />
	  <%= f.submit "Check College With Rank", class: "testersignup" %>
	<% end %>
		
		
		</div>
		
		</body>

</html>